/**
 * Phase 26 — extractor replay harness.
 *
 * Runs the CURRENT extractors against the raw `source.html` checked
 * into `.fixtures/by-filing/<company>/<filing>/source.html` and
 * compares per-filing counts against the frozen JSON outputs sitting
 * next to each source.html. The frozen outputs were generated by the
 * extractor version that ran at fixture-freeze time; the deltas
 * surface every extractor improvement that has landed since without
 * a re-freeze.
 *
 * This suite is gated behind `EXTRACTOR_REPLAY=1` and runs in
 * `describe.runIf(...)` mode because:
 *   1. `.fixtures/by-filing/<...>/source.html` is gitignored; CI
 *      doesn't have these files locally.
 *   2. Replay is intentionally read-only against the current code.
 *      It must never mutate fixtures — refreezing would mask the
 *      pre-Phase-11 peer-panel pollution that production still
 *      carries.
 *
 * Usage:
 *   EXTRACTOR_REPLAY=1 npx vitest run src/lib/extractors/extractor-replay.test.ts
 *
 * The output table goes to console; expectations are intentionally
 * lenient (no current count must regress below the frozen count).
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { extractCdAndA } from "./cd-and-a";
import { extractExecutiveCompensation } from "./executive-comp";
import { extractFactsFromSections } from "./facts";
import { extractPeerGroups } from "./peer-groups";
import { extractProxySections } from "./proxy-sections";

interface FilingCounts {
  exec: number;
  policy: number;
  metric: number;
  peer_groups: number;
  peer_members: number;
}

interface Delta {
  company: string;
  filing: string;
  frozen: FilingCounts;
  replay: FilingCounts;
}

const FIXTURES_ROOT = join(process.cwd(), ".fixtures", "by-filing");
const enabled =
  process.env.EXTRACTOR_REPLAY === "1" && existsSync(FIXTURES_ROOT);

function loadJson<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch {
    return null;
  }
}

function frozenCounts(dir: string): FilingCounts {
  const exec = loadJson<unknown[]>(join(dir, "executive_comp.json")) ?? [];
  const policy = loadJson<unknown[]>(join(dir, "policy_facts.json")) ?? [];
  const metric = loadJson<unknown[]>(join(dir, "metric_facts.json")) ?? [];
  const peer_groups =
    loadJson<{ members?: unknown[] }[]>(join(dir, "peer_groups.json")) ?? [];
  const peer_members = peer_groups.reduce(
    (acc, g) => acc + (g.members?.length ?? 0),
    0,
  );
  return {
    exec: exec.length,
    policy: policy.length,
    metric: metric.length,
    peer_groups: peer_groups.length,
    peer_members,
  };
}

function replayCounts(html: string): FilingCounts {
  const sections = extractProxySections(html);
  const cda = extractCdAndA(html);

  const sectionInputs = sections.map((r) => ({
    section_type: r.section_type,
    text: r.section.text,
    heading: r.section.heading,
  }));
  if (cda) {
    sectionInputs.push({
      section_type: "cd_and_a",
      text: cda.text,
      heading: cda.heading,
    });
  }
  const facts = extractFactsFromSections("replay", sectionInputs);

  const exec = extractExecutiveCompensation(html);
  const peers = cda ? extractPeerGroups("replay", cda.text) : [];
  const peer_members = peers.reduce(
    (acc, g) => acc + (g.members?.length ?? 0),
    0,
  );

  return {
    exec: exec.length,
    policy: facts.policies.length,
    metric: facts.metrics.length,
    peer_groups: peers.length,
    peer_members,
  };
}

function discoverFilings(): { company: string; filing: string; dir: string }[] {
  if (!existsSync(FIXTURES_ROOT)) return [];
  const out: { company: string; filing: string; dir: string }[] = [];
  for (const company of readdirSync(FIXTURES_ROOT).sort()) {
    const cdir = join(FIXTURES_ROOT, company);
    let kids: string[];
    try {
      kids = readdirSync(cdir);
    } catch {
      continue;
    }
    for (const filing of kids.filter((f) => /^\d/.test(f)).sort()) {
      const fdir = join(cdir, filing);
      if (existsSync(join(fdir, "source.html"))) {
        out.push({ company, filing, dir: fdir });
      }
    }
  }
  return out;
}

describe.runIf(enabled)("extractor replay vs frozen fixtures (Phase 26)", () => {
  const filings = discoverFilings();

  it("discovers at least one fixture filing with source.html", () => {
    expect(filings.length).toBeGreaterThan(0);
  });

  const deltas: Delta[] = [];

  for (const { company, filing, dir } of filings) {
    it(`${company}/${filing}: replay counts do not regress vs frozen`, () => {
      const html = readFileSync(join(dir, "source.html"), "utf8");
      const frozen = frozenCounts(dir);
      const replay = replayCounts(html);
      deltas.push({ company, filing, frozen, replay });

      // Phase 26 contract:
      //   - exec / policy / metric counts must NOT regress. These are
      //     deterministic-fact rows; a drop means the extractor lost
      //     real data, not noise.
      //   - peer_groups MAY drop, because Phase 11 / 11.5 / 16 added
      //     suppression rules for single-token alias false positives
      //     (the pollution under recovery). A frozen fixture that
      //     contained noise can correctly produce 0 groups today and
      //     that's an improvement, not a regression. The drop is
      //     reported in the per-filing log line below.
      expect(replay.exec, `exec rows on ${company}/${filing}`).toBeGreaterThanOrEqual(
        frozen.exec,
      );
      expect(
        replay.policy,
        `policy facts on ${company}/${filing}`,
      ).toBeGreaterThanOrEqual(frozen.policy);
      expect(
        replay.metric,
        `metric facts on ${company}/${filing}`,
      ).toBeGreaterThanOrEqual(frozen.metric);
      // peer_groups: log only, no assertion. See contract above.
      const sign = (a: number, b: number) =>
        a > b ? `+${a - b}` : a < b ? `${a - b}` : "·";
      const tag =
        replay.peer_groups < frozen.peer_groups
          ? "[noise-suppressed]"
          : replay.peer_groups > frozen.peer_groups
            ? "[improved]"
            : "";
      console.log(
        `  ${company}/${filing}: ` +
          `exec ${replay.exec}(${sign(replay.exec, frozen.exec)})  ` +
          `policy ${replay.policy}(${sign(replay.policy, frozen.policy)})  ` +
          `metric ${replay.metric}(${sign(replay.metric, frozen.metric)})  ` +
          `peers ${replay.peer_groups}(${sign(replay.peer_groups, frozen.peer_groups)})  ` +
          `members ${replay.peer_members}(${sign(replay.peer_members, frozen.peer_members)}) ${tag}`,
      );
    });
  }
});

describe.runIf(!enabled)("extractor replay (gated)", () => {
  it("is skipped unless EXTRACTOR_REPLAY=1 and .fixtures/by-filing exists locally", () => {
    expect(true).toBe(true);
  });
});
