/**
 * Phase 26 — extractor replay harness.
 *
 * Runs the CURRENT extractors against the raw `source.html` checked
 * into `.fixtures/by-filing/<company>/<filing>/source.html` and
 * compares per-filing counts against the frozen JSON outputs sitting
 * next to each source.html. The frozen outputs were generated by the
 * extractor version that ran at fixture-freeze time; the deltas
 * surface every extractor improvement that has landed since without
 * a re-freeze.
 *
 * This suite is gated behind `EXTRACTOR_REPLAY=1` and runs in
 * `describe.runIf(...)` mode because:
 *   1. `.fixtures/by-filing/<...>/source.html` is gitignored; CI
 *      doesn't have these files locally.
 *   2. Replay is intentionally read-only against the current code.
 *      It must never mutate fixtures — refreezing would mask the
 *      pre-Phase-11 peer-panel pollution that production still
 *      carries.
 *
 * Usage:
 *   EXTRACTOR_REPLAY=1 npx vitest run src/lib/extractors/extractor-replay.test.ts
 *
 * The output table goes to console. What a replay delta MEANS depends on
 * the freeze source: a legacy SQLite-oracle freeze keeps the strict
 * no-regression floor, while a post-recovery Postgres (production-*) freeze
 * is informational (counts may differ in either direction, and only a
 * catastrophic "facts in the freeze but none on replay" fails). See the
 * per-filing Phase 26 / 33 contract block below for the authoritative rules.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { extractCdAndA } from "./cd-and-a";
import { extractExecutiveCompensation } from "./executive-comp";
import { extractFactsFromSections } from "./facts";
import { extractPeerGroups } from "./peer-groups";
import { extractProxySections } from "./proxy-sections";

interface FilingCounts {
  exec: number;
  policy: number;
  metric: number;
  peer_groups: number;
  peer_members: number;
}

interface Delta {
  company: string;
  filing: string;
  frozen: FilingCounts;
  replay: FilingCounts;
}

const FIXTURES_ROOT = join(process.cwd(), ".fixtures", "by-filing");
const enabled =
  process.env.EXTRACTOR_REPLAY === "1" && existsSync(FIXTURES_ROOT);

function loadJson<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch {
    return null;
  }
}

function frozenCounts(dir: string): FilingCounts {
  const exec = loadJson<unknown[]>(join(dir, "executive_comp.json")) ?? [];
  const policy = loadJson<unknown[]>(join(dir, "policy_facts.json")) ?? [];
  const metric = loadJson<unknown[]>(join(dir, "metric_facts.json")) ?? [];
  const peer_groups =
    loadJson<{ members?: unknown[] }[]>(join(dir, "peer_groups.json")) ?? [];
  const peer_members = peer_groups.reduce(
    (acc, g) => acc + (g.members?.length ?? 0),
    0,
  );
  return {
    exec: exec.length,
    policy: policy.length,
    metric: metric.length,
    peer_groups: peer_groups.length,
    peer_members,
  };
}

function replayCounts(html: string): FilingCounts {
  const sections = extractProxySections(html);
  const cda = extractCdAndA(html);

  const sectionInputs = sections.map((r) => ({
    section_type: r.section_type,
    text: r.section.text,
    heading: r.section.heading,
  }));
  if (cda) {
    sectionInputs.push({
      section_type: "cd_and_a",
      text: cda.text,
      heading: cda.heading,
    });
  }
  const facts = extractFactsFromSections("replay", sectionInputs);

  const exec = extractExecutiveCompensation(html);
  const peers = cda ? extractPeerGroups("replay", cda.text) : [];
  const peer_members = peers.reduce(
    (acc, g) => acc + (g.members?.length ?? 0),
    0,
  );

  return {
    exec: exec.length,
    policy: facts.policies.length,
    metric: facts.metrics.length,
    peer_groups: peers.length,
    peer_members,
  };
}

function discoverFilings(): { company: string; filing: string; dir: string }[] {
  if (!existsSync(FIXTURES_ROOT)) return [];
  const out: { company: string; filing: string; dir: string }[] = [];
  for (const company of readdirSync(FIXTURES_ROOT).sort()) {
    const cdir = join(FIXTURES_ROOT, company);
    let kids: string[];
    try {
      kids = readdirSync(cdir);
    } catch {
      continue;
    }
    for (const filing of kids.filter((f) => /^\d/.test(f)).sort()) {
      const fdir = join(cdir, filing);
      if (existsSync(join(fdir, "source.html"))) {
        out.push({ company, filing, dir: fdir });
      }
    }
  }
  return out;
}

describe.runIf(enabled)("extractor replay vs frozen fixtures (Phase 26)", () => {
  const filings = discoverFilings();
  // The freeze source decides what a replay delta MEANS (see the per-filing
  // contract below). Legacy SQLite-oracle freeze = a true offline baseline;
  // post-recovery Postgres freeze = a snapshot of production's richer
  // ingestion pipeline.
  const frozenSource =
    loadJson<{ source?: string }>(join(FIXTURES_ROOT, "..", "FROZEN.json"))
      ?.source ?? "";
  const productionSourced = /^production/i.test(frozenSource);

  it("discovers at least one fixture filing with source.html", () => {
    expect(filings.length).toBeGreaterThan(0);
  });

  const deltas: Delta[] = [];

  for (const { company, filing, dir } of filings) {
    it(`${company}/${filing}: offline replay vs frozen fixture counts`, () => {
      const html = readFileSync(join(dir, "source.html"), "utf8");
      const frozen = frozenCounts(dir);
      const replay = replayCounts(html);
      deltas.push({ company, filing, frozen, replay });

      // Phase 26 / 33 contract — what a replay delta means depends on the
      // freeze source:
      //
      //   Legacy SQLite-oracle freeze (frozenSource is empty / "oracle"):
      //   frozen was produced by the SAME deterministic extractors this
      //   harness re-runs, so it is a true offline baseline. exec / policy /
      //   metric must NOT regress below it — a drop means the extractor lost
      //   real data. peer_groups MAY drop (Phase 11 / 11.5 / 16 alias
      //   suppression turns frozen noise into 0 groups, an improvement).
      //
      //   Post-recovery Postgres freeze (source "production-*"): frozen is a
      //   snapshot of production's richer ingestion pipeline, not this
      //   offline harness. Offline replay and frozen legitimately differ in
      //   EITHER direction on any dimension (production extracts a pay-ratio
      //   metric the offline path misses on googl/000130817923000736; the
      //   offline path finds peer groups a limit-bounded re-ingest never
      //   refreshed on meta/000132680124000034). The strict floor is
      //   meaningless here, so we log the deltas and only fail on a
      //   CATASTROPHIC offline failure: a filing that has facts in the freeze
      //   but yields none on replay. Genuine offline-extractor regressions
      //   stay covered by the extractor unit / parity tests (which run in CI
      //   against their own expectations, not production fixtures).
      const frozenFacts = frozen.exec + frozen.policy + frozen.metric;
      const replayFacts = replay.exec + replay.policy + replay.metric;
      if (productionSourced) {
        if (frozenFacts > 0) {
          expect(
            replayFacts,
            `offline extractor produced 0 exec/policy/metric facts on ` +
              `${company}/${filing} while the production freeze has ` +
              `${frozenFacts} — the offline extractor looks broken`,
          ).toBeGreaterThan(0);
        }
      } else {
        expect(replay.exec, `exec rows on ${company}/${filing}`).toBeGreaterThanOrEqual(
          frozen.exec,
        );
        expect(
          replay.policy,
          `policy facts on ${company}/${filing}`,
        ).toBeGreaterThanOrEqual(frozen.policy);
        expect(
          replay.metric,
          `metric facts on ${company}/${filing}`,
        ).toBeGreaterThanOrEqual(frozen.metric);
      }
      // peer_groups: log only in both regimes. See contract above.
      const sign = (a: number, b: number) =>
        a > b ? `+${a - b}` : a < b ? `${a - b}` : "·";
      const tag =
        replay.peer_groups < frozen.peer_groups
          ? "[noise-suppressed]"
          : replay.peer_groups > frozen.peer_groups
            ? "[improved]"
            : "";
      console.log(
        `  ${company}/${filing}: ` +
          `exec ${replay.exec}(${sign(replay.exec, frozen.exec)})  ` +
          `policy ${replay.policy}(${sign(replay.policy, frozen.policy)})  ` +
          `metric ${replay.metric}(${sign(replay.metric, frozen.metric)})  ` +
          `peers ${replay.peer_groups}(${sign(replay.peer_groups, frozen.peer_groups)})  ` +
          `members ${replay.peer_members}(${sign(replay.peer_members, frozen.peer_members)}) ${tag}`,
      );
    });
  }
});

describe.runIf(!enabled)("extractor replay (gated)", () => {
  it("is skipped unless EXTRACTOR_REPLAY=1 and .fixtures/by-filing exists locally", () => {
    expect(true).toBe(true);
  });
});
